name: Common CI
on:
  workflow_call:
    input:
      common_name:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo Build

  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo Tesst

  Dev-Deployment:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run:  echo Deploy
      - name: Deploy
        run:  make component=${{ inputs.component_name }} env=dev


