name: Common CI
on:
  workflow_call:
    inputs:
      common_name:
        required: true
        type: string

jobs:
  Download-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo Build

  Test:
    runs-on: ubuntu-latest
    needs: Download-Dependencies
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo Test

  DockerBuild-n-Push:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo Test


  Dev-Deployment:
    runs-on: ubuntu-latest
    needs: DockerBuild-n-Push
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run:  echo Deploy



  QA-Deployment:
    runs-on: ubuntu-latest
    needs: Dev-Deployment
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run:  echo Deploy
      - name: Deploy


  PROD-Deployment:
    runs-on: ubuntu-latest
    needs: QA-Deployment
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run:  echo Deploy
